name: Deploy with Cleanup

on:
  workflow_dispatch:

jobs:
  expressions:
    runs-on: ubuntu-latest
    steps:
      - name: Run a deployment script
        run: ./deploy.sh
      - name: Cleanup on failure
        run: echo "Deployment succeeded"
        if: success()
        # always() -> always runs regardless of the previous step result
        # cancelled() -> if the previous step was cancelled
