name: Manual WorkFlow # name of the workflow

on:
  workflow_dispatch: # allows manual triggering via GitHub UI, CLI (gh workflow run), or REST API
    inputs: # inputs for the workflow
      environment:
        description: "Environment to deploy to"
        required: true
        default: "quality"
        type: choice
        options:
          - quality
          - production

jobs:
  deploy: # job name
    runs-on: ubuntu-latest # runner
    steps:
      - name: Deploy application # step name
        run: echo "Deploying the application .." # run shell command
